#!/usr/bin/env node
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import chalk from "chalk";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const projectName = process.argv[2];

if (!projectName) {
  console.log("❗ Usage: create-myfolder <project-name>");
  process.exit(1);
}

const projectPath = path.join(process.cwd(), projectName);

const gitignoreContent = `# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*
.pnpm-debug.log*

# Diagnostic reports (https://nodejs.org/api/report.html)
report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage
*.lcov

# nyc test coverage
.nyc_output

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules/
jspm_packages/

# Snowpack dependency directory (https://snowpack.dev/)
web_modules/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Optional stylelint cache
.stylelintcache

# Microbundle cache
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variable files
.env
.env.development.local
.env.test.local
.env.production.local
.env.local

# parcel-bundler cache (https://parceljs.org/)
.cache
.parcel-cache

# Next.js build output
.next
out

# Nuxt.js build / generate output
.nuxt
dist

# Gatsby files
.cache/
# Comment in the public line in if your project uses Gatsby and not Next.js
# https://nextjs.org/blog/next-9-1#public-directory-support
# public

# vuepress build output
.vuepress/dist

# vuepress v2.x temp and cache directory
.temp
.cache

# vitepress build output
**/.vitepress/dist

# vitepress cache directory
**/.vitepress/cache

# Docusaurus cache and generated files
.docusaurus

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# TernJS port file
.tern-port

# Stores VSCode versions used for testing VSCode extensions
.vscode-test

# yarn v2
.yarn/cache
.yarn/unplugged
.yarn/build-state.yml
.yarn/install-state.gz
.pnp.*
`;

const gulpFileContent = `
const gulp = require("gulp");
const sass = require("gulp-sass")(require("sass"));
const sourcemaps = require("gulp-sourcemaps");
const concat = require("gulp-concat");
const minify = require("gulp-minify");
const cleanCss = require("gulp-clean-css");
const mmq = require("gulp-merge-media-queries");

// Development Tasks
gulp.task("sass", function () {
  return gulp
    .src("src/scss/**/*.scss") // Gets all files ending with .scss in src/scss and children dirs
    .pipe(sourcemaps.init())
    .pipe(sass().on("error", sass.logError)) // Passes it through a gulp-sass, log errors to console
    .pipe(cleanCss()) // Minifying the CSS
    .pipe(mmq()) // Merging media queries
    .pipe(sourcemaps.write())
    .pipe(gulp.dest("src/css")); // Outputs it in the css folder
});

// Watchers
gulp.task("watch", function () {
  gulp.watch("src/scss/**/*.scss", gulp.series("sass"));
});

// Gulp task to minify CSS files
gulp.task("minifycss", function () {
  return (
    gulp
      .src(["src/css/style.css"])
      // Compile SASS files
      .pipe(
        sass({
          precision: 10,
          includePaths: ["."],
          onError: console.error.bind(console, "Sass error:"),
        })
      )
      .pipe(concat("bundle.min.css"))

      .pipe(cleanCss())
      // Output
      .pipe(gulp.dest("src/css"))
  );
});

// Gulp task to minify JavaScript files
gulp.task("minifyjs", function () {
  return (
    gulp
      .src(["src/js/index.js"])
      // Minify the file
      .pipe(concat("bundle.min.js"))
      .pipe(
        minify({
          ext: {
            min: ".js",
          },
          noSource: true,
        })
      )
      // Output
      .pipe(gulp.dest("src/js"))
  );
});

`;

const indexHtmlContent = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="author" content="Rohit Kumar" />
    <meta name="description" content="Your Project Description" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Your Project Title</title>

    <!-- Favicon Start  -->
    <link rel="icon" href="src/icons/favicon.ico" type="image/x-icon" />
    <link
      rel="apple-touch-icon"
      sizes="180x180"
      href="src/icons/apple-touch-icon.png"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="32x32"
      href="src/icons/favicon-32x32.png"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="16x16"
      href="src/icons/favicon-16x16.png"
    />
    <link rel="manifest" href="src/icons/site.webmanifest" />
    <!-- Favicon End  -->

    <!-- Custom CSS Start  -->
    <link rel="stylesheet" href="src/css/style.css" />
    <!-- Custom CSS End  -->
  </head>

  <body>
    <div class="container">
      <div class="wrapper">
        <span class="material-icons-sharp"> home </span>
        <h1 class="bg-primary-700 text-white-900 p-3">hello</h1>
      </div>
    </div>

    <!-- Owl Carousel Start -->
    <script src="src/js/jquery/jquery.min.js"></script>
    <script src="src/js/owl_carousel/owl.carousel.min.js"></script>
    <!-- Owl Carousel End  -->

    <!-- Bootstrap  JS Start -->
    <script src="src/js/bootstrap/bootstrap.bundle.min.js"></script>
    <!-- Bootstrap  JS End  -->

    <!-- Custom JS Start -->
    <script src="src/js/index.js"></script>
    <!-- Custom JS End -->
  </body>
</html>
`;

const packageContent = `{
  "name": "${projectName}",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "gulp watch",
    "gulp-minifycss": "gulp minifycss",
    "gulp-minifyjs": "gulp minifyjs",
    "build": "concurrently \\\"npm run gulp-minifycss\\\" \\\"npm run gulp-minifyjs\\\""
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "concurrently": "^9.0.0",
    "gulp": "^4.0.2",
    "gulp-autoprefixer": "^8.0.0",
    "gulp-clean-css": "^4.3.0",
    "gulp-concat": "^2.6.1",
    "gulp-csso": "^4.0.1",
    "gulp-merge-media-queries": "^0.2.1",
    "gulp-minify": "^3.1.0",
    "gulp-sass": "^5.1.0",
    "gulp-sourcemaps": "^3.0.0",
    "sass": "^1.54.5"
  },
  "dependencies": {
    "bootstrap": "^5.2.1"
  }
}`;

const indexJsContent = `console.log("JS file working!");

/* This is a function that is listening for the DOM to be ready. */
document.addEventListener("DOMContentLoaded", () => {
  initApp();
});

const initApp = () => {};

// querySelectorAll function
function qsAll(selector, parent = document) {
  return [...parent.querySelectorAll(selector)];
}

// querySelector function
function qs(selector, parent = document) {
  return parent.querySelector(selector);
}
`;

const styleScssContent = `@charset 'utf-8';
// Don't change the import folder links
@import "vendors/__vendors-dir.scss";
@import "utilities/__utilities-dir.scss";
@import "base/__base-dir.scss";
@import "components/__components-dir.scss";
@import "layout/__layout-dir.scss";
@import "pages/__pages-dir.scss";
`;

// ========== Utility Functions ==========
function writeFile(filePath, content) {
  fs.writeFileSync(filePath, content, "utf8");
}

function createFolders(paths) {
  paths.forEach((dir) => fs.mkdirSync(dir, { recursive: true }));
}

// ========== Main Execution ==========
try {
  if (fs.existsSync(projectPath)) {
    if (!forceFlag) {
      console.log(
        chalk.red(
          `❌ Folder "${projectName}" already exists. Use --force to overwrite.`
        )
      );
      process.exit(1);
    } else {
      fs.rmSync(projectPath, { recursive: true, force: true });
    }
  }

  // Directory Structure
  const srcPath = path.join(projectPath, "src");
  const jsPath = path.join(srcPath, "js");
  const scssPath = path.join(srcPath, "scss");

  const directories = [
    srcPath,
    path.join(srcPath, "fonts"),
    path.join(srcPath, "icons"),
    path.join(srcPath, "images"),
    jsPath,
    path.join(jsPath, "bootstrap"),
    path.join(jsPath, "jquery"),
    path.join(jsPath, "owl_carousel"),
    scssPath,
    path.join(scssPath, "base"),
    path.join(scssPath, "components"),
    path.join(scssPath, "layout"),
    path.join(scssPath, "pages"),
    path.join(scssPath, "utilities"),
    path.join(scssPath, "vendors"),
  ];

  createFolders(directories);

  // Write Files
  writeFile(path.join(jsPath, "index.js"), indexJsContent);
  writeFile(path.join(scssPath, "style.scss"), styleScssContent);
  writeFile(path.join(projectPath, ".gitignore"), gitignoreContent);
  writeFile(path.join(projectPath, "gulpfile.js"), gulpFileContent);
  writeFile(path.join(projectPath, "index.html"), indexHtmlContent);
  writeFile(path.join(projectPath, "package.json"), packageContent);

  console.log(chalk.green(`✅ Project "${projectName}" created successfully!`));
} catch (err) {
  console.error(
    chalk.red(`❌ Error creating project "${projectName}": ${err.message}`)
  );
  process.exit(1);
}
