#!/usr/bin/env node
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import chalk from "chalk";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const projectName = process.argv[2];

if (!projectName) {
  console.log("❗ Usage: create-myfolder <project-name>");
  process.exit(1);
}

const projectPath = path.join(process.cwd(), projectName);

const gitignoreContent = `# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*
.pnpm-debug.log*

# Diagnostic reports (https://nodejs.org/api/report.html)
report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage
*.lcov

# nyc test coverage
.nyc_output

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules/
jspm_packages/

# Snowpack dependency directory (https://snowpack.dev/)
web_modules/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Optional stylelint cache
.stylelintcache

# Microbundle cache
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variable files
.env
.env.development.local
.env.test.local
.env.production.local
.env.local

# parcel-bundler cache (https://parceljs.org/)
.cache
.parcel-cache

# Next.js build output
.next
out

# Nuxt.js build / generate output
.nuxt
dist

# Gatsby files
.cache/
# Comment in the public line in if your project uses Gatsby and not Next.js
# https://nextjs.org/blog/next-9-1#public-directory-support
# public

# vuepress build output
.vuepress/dist

# vuepress v2.x temp and cache directory
.temp
.cache

# vitepress build output
**/.vitepress/dist

# vitepress cache directory
**/.vitepress/cache

# Docusaurus cache and generated files
.docusaurus

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# TernJS port file
.tern-port

# Stores VSCode versions used for testing VSCode extensions
.vscode-test

# yarn v2
.yarn/cache
.yarn/unplugged
.yarn/build-state.yml
.yarn/install-state.gz
.pnp.*
`;

const gulpFileContent = `
const gulp = require("gulp");
const sass = require("gulp-sass")(require("sass"));
const sourcemaps = require("gulp-sourcemaps");
const concat = require("gulp-concat");
const minify = require("gulp-minify");
const cleanCss = require("gulp-clean-css");
const mmq = require("gulp-merge-media-queries");

// Development Tasks
gulp.task("sass", function () {
  return gulp
    .src("src/scss/**/*.scss") // Gets all files ending with .scss in src/scss and children dirs
    .pipe(sourcemaps.init())
    .pipe(sass().on("error", sass.logError)) // Passes it through a gulp-sass, log errors to console
    .pipe(cleanCss()) // Minifying the CSS
    .pipe(mmq()) // Merging media queries
    .pipe(sourcemaps.write())
    .pipe(gulp.dest("src/css")); // Outputs it in the css folder
});

// Watchers
gulp.task("watch", function () {
  gulp.watch("src/scss/**/*.scss", gulp.series("sass"));
});

// Gulp task to minify CSS files
gulp.task("minifycss", function () {
  return (
    gulp
      .src(["src/css/style.css"])
      // Compile SASS files
      .pipe(
        sass({
          precision: 10,
          includePaths: ["."],
          onError: console.error.bind(console, "Sass error:"),
        })
      )
      .pipe(concat("bundle.min.css"))

      .pipe(cleanCss())
      // Output
      .pipe(gulp.dest("src/css"))
  );
});

// Gulp task to minify JavaScript files
gulp.task("minifyjs", function () {
  return (
    gulp
      .src(["src/js/index.js"])
      // Minify the file
      .pipe(concat("bundle.min.js"))
      .pipe(
        minify({
          ext: {
            min: ".js",
          },
          noSource: true,
        })
      )
      // Output
      .pipe(gulp.dest("src/js"))
  );
});

`;

const indexHtmlContent = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="author" content="Rohit Kumar" />
    <meta name="description" content="Your Project Description" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Your Project Title</title>

    <!-- Favicon Start  -->
    <link rel="icon" href="src/icons/favicon.ico" type="image/x-icon" />
    <link
      rel="apple-touch-icon"
      sizes="180x180"
      href="src/icons/apple-touch-icon.png"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="32x32"
      href="src/icons/favicon-32x32.png"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="16x16"
      href="src/icons/favicon-16x16.png"
    />
    <link rel="manifest" href="src/icons/site.webmanifest" />
    <!-- Favicon End  -->

    <!-- Custom CSS Start  -->
    <link rel="stylesheet" href="src/css/style.css" />
    <!-- Custom CSS End  -->
  </head>

  <body>
    <div class="container">
      <div class="wrapper">
        <span class="material-icons-sharp"> home </span>
        <h1 class="bg-primary-700 text-white-900 p-3">hello</h1>
      </div>
    </div>

    <!-- Owl Carousel Start -->
    <script src="src/js/jquery/jquery.min.js"></script>
    <script src="src/js/owl_carousel/owl.carousel.min.js"></script>
    <!-- Owl Carousel End  -->

    <!-- Bootstrap  JS Start -->
    <script src="src/js/bootstrap/bootstrap.bundle.min.js"></script>
    <!-- Bootstrap  JS End  -->

    <!-- Custom JS Start -->
    <script src="src/js/index.js"></script>
    <!-- Custom JS End -->
  </body>
</html>
`;

const packageContent = `{
  "name": "${projectName}",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "gulp watch",
    "gulp-minifycss": "gulp minifycss",
    "gulp-minifyjs": "gulp minifyjs",
    "build": "concurrently \\\"npm run gulp-minifycss\\\" \\\"npm run gulp-minifyjs\\\""
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "concurrently": "^9.0.0",
    "gulp": "^4.0.2",
    "gulp-autoprefixer": "^8.0.0",
    "gulp-clean-css": "^4.3.0",
    "gulp-concat": "^2.6.1",
    "gulp-csso": "^4.0.1",
    "gulp-merge-media-queries": "^0.2.1",
    "gulp-minify": "^3.1.0",
    "gulp-sass": "^5.1.0",
    "gulp-sourcemaps": "^3.0.0",
    "sass": "^1.54.5"
  },
  "dependencies": {
    "bootstrap": "^5.2.1"
  }
}`;

const indexJsContent = `console.log("JS file working!");

/* This is a function that is listening for the DOM to be ready. */
document.addEventListener("DOMContentLoaded", () => {
  initApp();
});

const initApp = () => {};

// querySelectorAll function
function qsAll(selector, parent = document) {
  return [...parent.querySelectorAll(selector)];
}

// querySelector function
function qs(selector, parent = document) {
  return parent.querySelector(selector);
}
`;

const styleScssContent = `@charset 'utf-8';
// Don't change the import folder links
@import "vendors/__vendors-dir.scss";
@import "utilities/__utilities-dir.scss";
@import "base/__base-dir.scss";
@import "components/__components-dir.scss";
@import "layout/__layout-dir.scss";
@import "pages/__pages-dir.scss";
`;

const baseDirContent = `@import "base";
@import "typography";
`;

const baseContent = `html {
  box-sizing: border-box;
  font-size: 16px;
  color-scheme: light dark;
}

body {
  color: $black;
  background: $white;
  font-family: "Montserrat", sans-serif;
  font-weight: 400;
}

*,
*::before,
*::after {
  padding: 0;
  margin: 0;
  box-sizing: inherit;
}

h1,
h2,
h3,
h4,
h5,
h6,
p,
ol,
ul,
figure,
blockquote {
  padding: 0;
  margin: 0;
  font-weight: 400;
}

img,
picture,
svg {
  max-width: 100%;
  width: auto;
  height: auto;
}

img {
  font-style: italic;
  vertical-align: middle;
  background-repeat: no-repeat;
  background-size: cover;
  shape-margin: 16px;
}
`;

const componentsDirContent = `@import "button";
@import "dropdown";
`;

const layoutDirContent = `@import "footer";
@import "header";
@import "main";
@import "navigation";
@import "sidebar";
@import "layout";
`;

const layoutContent = `// .container {
//   max-width: 1000px;
//   width: 100%;
//   padding-inline: 16px;
//   margin-inline: auto;
// }

.container {
  --content: 1200px;
  --mw: 100%;
  --px: calc(15px * 2);

  width: min(var(--mw) - var(--px), var(--content));
  padding-inline: 0 !important; // if bootstrap install
  margin-inline: auto;
}

.grid-container {
  --width: 1200px;
  --px: 15px;

  display: grid;
  grid-template-columns:
    [full-width-start] minmax(var(--px), 1fr)
    [container-start]
    min(100% - (var(--px) * 2), var(--width))
    [container-end]
    minmax(var(--px), 1fr) [full-width-end];

  > * {
    grid-column: container;
  }

  > .full-width {
    grid-column: full-width;
  }
}

.grid-wrapper {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  grid-auto-rows: 200px;
  gap: 20px;
}
`;

const pagesDirContent = `@import "contact";
@import "login";
`;

const utilitiesDirContent = `@import "variables";
@import "extend";
@import "function";
@import "icons";
@import "mixins";
@import "utils";
`;

// ========== Utility Functions ==========
function writeFile(filePath, content) {
  fs.writeFileSync(filePath, content, "utf8");
  console.log(chalk.gray(`📝 ${filePath}`));
}

function createFolders(paths) {
  paths.forEach((dir) => fs.mkdirSync(dir, { recursive: true }));
}

// ========== Main Execution ==========
try {
  if (fs.existsSync(projectPath)) {
    if (!forceFlag) {
      console.log(chalk.red(`❌ Folder "${projectName}" already exists. Use --force to overwrite.`));
      process.exit(1);
    } else {
      fs.rmSync(projectPath, { recursive: true, force: true });
    }
  }

  // === Directory Structure ===
  const directories = [
    `${projectPath}/src/fonts`,
    `${projectPath}/src/icons`,
    `${projectPath}/src/images`,
    `${projectPath}/src/js`,
    `${projectPath}/src/js/bootstrap`,
    `${projectPath}/src/js/jquery`,
    `${projectPath}/src/js/owl_carousel`,
    `${projectPath}/src/scss/base`,
    `${projectPath}/src/scss/components`,
    `${projectPath}/src/scss/layout`,
    `${projectPath}/src/scss/pages`,
    `${projectPath}/src/scss/utilities`,
    `${projectPath}/src/scss/vendors`,
  ];

  createFolders(directories);

  // === File Definitions ===
  const files = [
    // JS
    [`${projectPath}/src/js/index.js`, indexJsContent],

    // SCSS Main Entry
    [`${projectPath}/src/scss/style.scss`, styleScssContent],

    // SCSS Base
    [`${projectPath}/src/scss/base/__base-dir.scss`, baseDirContent],
    [`${projectPath}/src/scss/base/_base.scss`, baseContent],
    [`${projectPath}/src/scss/base/_typography.scss`, ``],

    // SCSS Components
    [`${projectPath}/src/scss/components/__components-dir.scss`, componentsDirContent],
    [`${projectPath}/src/scss/components/_button.scss`, ``],
    [`${projectPath}/src/scss/components/_dropdown.scss`, ``],

    // SCSS Layout
    [`${projectPath}/src/scss/layout/__layout-dir.scss`, layoutDirContent],
    [`${projectPath}/src/scss/layout/_footer.scss`, ``],
    [`${projectPath}/src/scss/layout/_header.scss`, ``],
    [`${projectPath}/src/scss/layout/_layout.scss`, layoutContent],
    [`${projectPath}/src/scss/layout/_main.scss`, ``],
    [`${projectPath}/src/scss/layout/_navigation.scss`, ``],
    [`${projectPath}/src/scss/layout/_sidebar.scss`, ``],

    // SCSS Pages
    [`${projectPath}/src/scss/pages/__pages-dir.scss`, pagesDirContent],
    [`${projectPath}/src/scss/pages/_contact.scss`, ``],
    [`${projectPath}/src/scss/pages/_login.scss`, ``],

    // SCSS utilities
    [`${projectPath}/src/scss/utilities/__utilities-dir.scss`, utilitiesDirContent],
    [`${projectPath}/src/scss/utilities/`, ``],

    // Root Level
    [`${projectPath}/.gitignore`, gitignoreContent],
    [`${projectPath}/gulpfile.js`, gulpFileContent],
    [`${projectPath}/index.html`, indexHtmlContent],
    [`${projectPath}/package.json`, packageContent],
  ];

  files.forEach(([filePath, content]) => writeFile(filePath, content));

  console.log(chalk.green(`✅ Project "${projectName}" created successfully!`));
} catch (err) {
  console.error(chalk.red(`❌ Error creating project "${projectName}": ${err.message}`));
  process.exit(1);
}
